### ISSUE TITLE
Change default local bind port

### ISSUE THREAD

**Issue by chetan51** [chetan51/sidestep#13]
Change the default port to something other than the default vidalia/tor port.

**Comment by ghost** [comment]
Port 1080 is the default port for SOCKS.  

I was thinking about having Sidestep look to see if the local port was set to 9050 and providing a window to ask permission to reassign the port number. This way there's no nasty surprise for those who have configured apps to the original port number, and minimal confusion for those who simply want the app to "just work."

My thought is the window should only appear once in order to minimize the annoyance to the enduser.

**Comment by chetan51** [comment]
Good idea. Although 1080 is often used by servers that run on your local machine, even though it shouldn't be. Maybe we should choose a more obscure default port to make sure Sidestep doesn't conflict with anything else?

I've pulled your latest commits and released an update to Sidestep.

**Comment by ghost** [comment]
Perhaps port 60606 would do?  It doesn't show with any regularity in Google or Bing.

**Comment by chetan51** [comment]
Sure, that sounds fine.
